// SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
// SPDX-License-Identifier: GPL-3.0-or-later

import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// /l/<variant> short links redirect to the variant landing page
// /landing/<slug>/. The redirect pages are generated by
// scripts/build-pages.py from the same slug source as the landing
// pages themselves, so they can never go stale.

const manifest = JSON.parse(
  readFileSync(join(process.cwd(), "public", "variants.json"), "utf8")
);

for (const [variantId, { slug }] of Object.entries(manifest.variants)) {
  test(`/l/${variantId}/ redirects to /landing/${slug}/`, async ({
    page,
  }) => {
    await page.goto(`/l/${variantId}/`);
    await page.waitForURL(`**/landing/${slug}/`);
    await expect(page.locator("h1").first()).toBeVisible();
  });
}

test("landing page #waitlist anchor targets the waitlist section", async ({
  page,
}) => {
  await page.goto("/#waitlist");
  const section = page.locator("section#waitlist");
  await expect(section).toHaveClass(/waitlist-section/);
  // The anchor must actually scroll the section into view.
  await expect(section).toBeInViewport();
});
