// SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
// SPDX-License-Identifier: GPL-3.0-or-later

import { test, expect } from "@playwright/test";

// sitemap.xml is a sitemap INDEX aggregating three child sitemaps:
//   - sitemap-pages.xml  (marketing pages, generated by build-pages.py)
//   - blog/sitemap.xml   (generated by Zola)
//   - docs.vauchi.app    (cross-host, generated by the docs repo)
// These tests fail loudly if the index loses a child or the generated
// pages child is missing/empty (e.g. build-pages.py step skipped).

const CHILD_SITEMAPS = [
  "https://vauchi.app/sitemap-pages.xml",
  "https://vauchi.app/blog/sitemap.xml",
  "https://docs.vauchi.app/sitemap.xml",
];

test("sitemap.xml is an index referencing pages, blog and docs", async ({
  request,
}) => {
  const res = await request.get("/sitemap.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<sitemapindex");
  for (const loc of CHILD_SITEMAPS) {
    expect(body).toContain(`<loc>${loc}</loc>`);
  }
});

test("sitemap-pages.xml lists every localized home page", async ({
  request,
}) => {
  const res = await request.get("/sitemap-pages.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<urlset");
  // Default locale plus one entry per additional locale.
  expect(body).toContain("<loc>https://vauchi.app/</loc>");
  for (const loc of ["fr", "de", "it", "es"]) {
    expect(body).toContain(`<loc>https://vauchi.app/${loc}/</loc>`);
  }
  // The trailing-slash-after-.html bug that plagued the old hand-written
  // sitemaps must never appear.
  expect(body).not.toContain(".html/</loc>");
});

test("robots.txt advertises the sitemap index and the docs sitemap", async ({
  request,
}) => {
  const res = await request.get("/robots.txt");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("Sitemap: https://vauchi.app/sitemap.xml");
  expect(body).toContain("Sitemap: https://docs.vauchi.app/sitemap.xml");
});
