// SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
// SPDX-License-Identifier: GPL-3.0-or-later

import { test, expect } from "@playwright/test";

// sitemap.xml is a sitemap INDEX aggregating three child sitemaps:
//   - sitemap-pages.xml  (marketing pages, generated by build-pages.py)
//   - blog/sitemap.xml   (generated by Zola)
//   - docs/sitemap.xml   (generated by the docs repo; same-host since the
//                         2026-08 move off the docs.vauchi.app subdomain)
// These tests fail loudly if the index loses a child or the generated
// pages child is missing/empty (e.g. build-pages.py step skipped).

const CHILD_SITEMAPS = [
  "https://vauchi.app/sitemap-pages.xml",
  "https://vauchi.app/blog/sitemap.xml",
  "https://vauchi.app/docs/sitemap.xml",
];

test("sitemap.xml is an index referencing pages, blog and docs", async ({
  request,
}) => {
  const res = await request.get("/sitemap.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<sitemapindex");
  for (const loc of CHILD_SITEMAPS) {
    expect(body).toContain(`<loc>${loc}</loc>`);
  }
});

test("sitemap-pages.xml lists every localized home page", async ({
  request,
}) => {
  const res = await request.get("/sitemap-pages.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<urlset");
  // Default locale plus one entry per additional locale.
  expect(body).toContain("<loc>https://vauchi.app/</loc>");
  for (const loc of ["fr", "de", "it", "es"]) {
    expect(body).toContain(`<loc>https://vauchi.app/${loc}/</loc>`);
  }
  // The trailing-slash-after-.html bug that plagued the old hand-written
  // sitemaps must never appear.
  expect(body).not.toContain(".html/</loc>");
});

test("robots.txt advertises the sitemap index", async ({ request }) => {
  const res = await request.get("/robots.txt");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("Sitemap: https://vauchi.app/sitemap.xml");
  // The docs sitemap is a child of the index and lives on this host now.
  // A second cross-host Sitemap line would be stale, not redundant. Match
  // the directive rather than the bare host — the surrounding comment
  // explains the migration and legitimately names the old subdomain.
  expect(body).not.toMatch(/^Sitemap:.*docs\.vauchi\.app/m);
});

test("robots.txt separates answer engines from training crawlers", async ({
  request,
}) => {
  const res = await request.get("/robots.txt");
  const body = await res.text();
  // Blocking GPTBot while leaving OAI-SearchBot unlisted is the classic
  // half-configuration: it feeds training and keeps the search index.
  for (const allowed of ["OAI-SearchBot", "Claude-SearchBot", "PerplexityBot"]) {
    expect(body).toContain(`User-agent: ${allowed}`);
  }
  for (const blocked of ["GPTBot", "ClaudeBot", "Google-Extended", "CCBot"]) {
    expect(body).toContain(`User-agent: ${blocked}`);
  }
  const trainingGroup = body.slice(body.indexOf("User-agent: GPTBot"));
  expect(trainingGroup).toContain("Disallow: /");
});
